# -*- coding: utf-8 -*-
"""suc_ATH-MaaS_OvisOCR2_t4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STuokvmDrmpO8CWqyZWECtDoDbOP0fh3
"""









"""### https://huggingface.co/spaces/ATH-MaaS/OvisOCR2/blob/main/app.py

### https://huggingface.co/ATH-MaaS/OvisOCR2
"""







Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.14.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 25.1.0
aiohappyeyeballs                         2.7.1
aiohttp                                  3.14.1
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.12.0
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
anthropic                                0.121.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.14.2
anywidget                                0.9.21
apache-tvm-ffi                           0.1.9
apsw                                     3.53.3.1
apswutils                                0.1.2
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
astor                                    0.8.1
astropy                                  7.2.2
astropy-iers-data                        0.2026.7.13.0.54.2
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    26.1.0
audioread                                3.1.0
Authlib                                  1.7.2
autograd                                 1.9.1
babel                                    2.18.0
backcall                                 0.2.0
beartype                                 0.22.9
beautifulsoup4                           4.13.5
betterproto                              2.0.0b6
bigframes                                2.42.0
bigquery-magics                          0.14.0
blake3                                   1.0.9
bleach                                   6.4.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.2.0
blosc2                                   4.8.0
bokeh                                    3.8.2
Bottleneck                               1.4.2
bqplot                                   0.12.47
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               6.2.6
catalogue                                2.0.10
cbor2                                    6.1.4
certifi                                  2026.6.17
cffi                                     2.1.0
chardet                                  5.2.0
charset-normalizer                       3.4.9
clarabel                                 0.11.1
click                                    8.4.2
cligj                                    0.7.2
cloudpathlib                             0.24.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.2.1
colorlover                               0.3.0
community                                1.0.0b1
compressed-tensors                       0.15.0.1
confection                               1.3.3
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             49.0.0
cucim-cu12                               26.2.0
cuda-bindings                            12.9.7
cuda-core                                0.3.2
cuda-pathfinder                          1.5.6
cuda-python                              12.9.7
cuda-tile                                1.5.0
cuda-toolkit                             12.8.1
cudf-cu12                                26.2.1
cudf-polars-cu12                         26.2.1
cufflinks                                0.17.3
cuml-cu12                                26.2.0
cupy-cuda12x                             14.0.1
curl_cffi                                0.15.0
cuvs-cu12                                26.2.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dask                                     2026.1.1
dask-cuda                                26.2.0
dask-cudf-cu12                           26.2.1
dataproc-spark-connect                   1.1.0
datasets                                 4.0.0
db-dtypes                                1.7.1
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
deprecation                              2.1.0
depyf                                    0.20.0
detect-installer                         0.1.0
diffusers                                0.39.0
dill                                     0.3.8
diskcache                                5.6.3
distributed                              2026.1.1
distributed-ucxx-cu12                    0.48.0
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.10
dnspython                                2.8.0
docstring_parser                         0.18.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.7.35
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.2
email-validator                          2.3.0
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.9.0
et_xmlfile                               2.0.0
etils                                    1.14.0
etuples                                  0.3.10
Farama-Notifications                     0.0.6
fastai                                   2.8.7
fastapi                                  0.139.0
fastapi-cli                              0.0.32
fastapi-cloud-cli                        0.23.0
fastar                                   0.11.0
fastcore                                 2.0.5
fastdownload                             0.0.7
fastjsonschema                           2.21.2
fastlite                                 0.2.4
fastprogress                             1.1.6
fastsafetensors                          0.3.3
fasttransform                            0.0.2
filelock                                 3.29.7
firebase-admin                           6.9.0
flashinfer-cubin                         0.6.11.post2
flashinfer-python                        0.6.11.post2
Flask                                    3.1.3
flatbuffers                              25.12.19
flax                                     0.11.2
folium                                   0.20.0
fonttools                                4.63.0
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.7.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.2
geemap                                   0.38.3
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.4
geopy                                    2.4.1
gguf                                     0.19.0
giddy                                    2.3.6
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.51
glob2                                    0.7
google                                   3.0.0
google-adk                               2.4.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.30.3
google-api-python-client                 2.198.0
google-auth                              2.49.0
google-auth-httplib2                     0.4.0
google-auth-oauthlib                     1.4.0
google-cloud-bigquery                    3.42.2
google-cloud-bigquery-connection         1.22.0
google-cloud-bigquery-storage            2.39.0
google-cloud-core                        2.6.0
google-cloud-dataproc                    5.28.0
google-cloud-datastore                   2.25.0
google-cloud-firestore                   2.27.0
google-cloud-functions                   1.24.0
google-cloud-language                    2.21.0
google-cloud-monitoring                  2.31.0
google-cloud-resource-manager            1.18.0
google-cloud-spanner                     3.68.0
google-cloud-storage                     3.13.0
google-cloud-translate                   3.27.0
google-colab                             1.0.0
google-crc32c                            1.8.0
google-genai                             2.11.0
google-generativeai                      0.8.6
google-pasta                             0.2.0
google-resumable-media                   2.10.0
googleapis-common-protos                 1.75.0
googledrivedownloader                    1.1.0
gradio                                   6.22.0
gradio_client                            2.6.0
grain                                    0.2.18
graphviz                                 0.21
greenlet                                 3.5.3
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.4
grpc-interceptor                         0.15.4
grpcio                                   1.82.1
grpcio-status                            1.71.2
grpclib                                  0.4.9
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.3.0
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.8.1
h5py                                     3.16.0
hdbscan                                  0.8.44
hf-gradio                                0.4.1
hf-xet                                   1.5.1
highspy                                  1.15.1
holidays                                 0.100
holoviews                                1.23.1
hpack                                    4.2.0
html5lib                                 1.1
httpcore                                 1.0.9
httpcore2                                2.5.0
httpimport                               1.4.1
httplib2                                 0.32.0
httptools                                0.8.0
httpx                                    0.28.1
httpx2                                   2.5.0
huggingface_hub                          1.23.0
humanize                                 4.16.0
humming-kernels                          0.1.2
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.18
ijson                                    3.5.1
ImageIO                                  2.37.3
imageio-ffmpeg                           0.6.0
imagesize                                2.0.0
imbalanced-learn                         0.14.2
immutabledict                            4.3.1
importlib_metadata                       9.0.0
importlib_resources                      7.1.0
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.3
intel-openmp                             2025.3.3
interegular                              0.3.3
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.1.2
jaraco.functools                         4.5.0
jax                                      0.7.2
jax-cuda12-pjrt                          0.7.2
jax-cuda12-plugin                        0.7.2
jaxlib                                   0.7.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.16.0
jmespath                                 1.1.0
joblib                                   1.5.3
joserfc                                  1.7.3
jsonpatch                                1.33
jsonpickle                               4.1.2
jsonpointer                              3.1.1
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.1
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.20.0
jupyter_server_terminals                 0.5.4
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.19.4
kaggle                                   2.0.2
kagglehub                                1.0.2
kagglesdk                                0.1.23
keras                                    3.13.2
keras-hub                                0.26.0
keras-nlp                                0.26.0
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.5.0
langchain                                1.3.13
langchain-core                           1.4.9
langchain-protocol                       0.0.18
langgraph                                1.2.9
langgraph-checkpoint                     4.1.1
langgraph-prebuilt                       1.1.0
langgraph-sdk                            0.4.2
langsmith                                0.10.2
lark                                     1.2.2
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy-loader                              0.5
libclang                                 18.1.1
libcudf-cu12                             26.2.1
libcugraph-cu12                          26.2.0
libcuml-cu12                             26.2.0
libcuvs-cu12                             26.2.0
libkvikio-cu12                           26.2.0
libpysal                                 4.14.1
libraft-cu12                             26.2.0
librmm-cu12                              26.2.0
librosa                                  0.11.0
libucx-cu12                              1.19.0
libucxx-cu12                             0.48.0
lightgbm                                 4.6.0
linkify-it-py                            2.1.0
llguidance                               1.7.6
llvmlite                                 0.47.0
lm-format-enforcer                       0.11.3
locket                                   1.0.0
logical-unification                      0.4.7
loguru                                   0.7.3
lxml                                     6.1.1
Mako                                     1.1.3
mapclassify                              2.10.0
Markdown                                 3.10.2
markdown-it-py                           4.2.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.2
matplotlib-venn                          1.1.2
mcp                                      2.0.0
mcp-types                                2.0.0
mdit-py-plugins                          0.6.1
mdurl                                    0.1.2
mgwr                                     2.2.1
miniKanren                               1.0.5
missingno                                0.5.2
mistral_common                           1.11.7
mistune                                  3.3.3
mizani                                   0.13.5
mkl                                      2025.3.1
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
mmh3                                     5.2.1
model-hosting-container-standards        0.1.16
momepy                                   0.11.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.2.1
msgspec                                  0.21.1
multidict                                6.7.1
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.13
murmurhash                               1.0.15
music21                                  9.9.2
namex                                    0.1.0
narwhals                                 2.24.0
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.4
nbconvert                                7.17.1
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6.1
nh3                                      0.3.6
nibabel                                  5.4.2
ninja                                    1.13.0
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.65.0
numba-cuda                               0.22.2
numexpr                                  2.14.1
numpy                                    2.0.2
nvidia-cublas-cu12                       12.8.4.1
nvidia-cuda-cccl                         13.3.3.4.1
nvidia-cuda-cccl-cu12                    12.9.27
nvidia-cuda-crt                          13.3.73
nvidia-cuda-cupti-cu12                   12.8.90
nvidia-cuda-nvcc                         13.3.73
nvidia-cuda-nvcc-cu12                    12.8.93
nvidia-cuda-nvrtc                        13.3.33
nvidia-cuda-nvrtc-cu12                   12.8.93
nvidia-cuda-runtime                      13.3.29
nvidia-cuda-runtime-cu12                 12.8.90
nvidia-cudnn-cu12                        9.19.0.56
nvidia-cudnn-frontend                    1.18.0
nvidia-cufft-cu12                        11.3.3.83
nvidia-cufile-cu12                       1.13.1.3
nvidia-curand-cu12                       10.3.9.90
nvidia-cusolver-cu12                     11.7.3.90
nvidia-cusparse-cu12                     12.5.8.93
nvidia-cusparselt-cu12                   0.7.1
nvidia-cutlass-dsl                       4.5.2
nvidia-cutlass-dsl-libs-base             4.5.2
nvidia-cutlass-dsl-libs-cu13             4.5.2
nvidia-libnvcomp-cu12                    5.1.0.21
nvidia-ml-py                             13.610.43
nvidia-nccl-cu12                         2.28.9
nvidia-nvimgcodec-cu12                   0.7.0.11
nvidia-nvjitlink-cu12                    12.8.93
nvidia-nvshmem-cu12                      3.4.5
nvidia-nvtx-cu12                         12.8.90
nvidia-nvvm                              13.3.73
nvtx                                     0.2.15
nx-cugraph-cu12                          26.2.0
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.1
onemkl-license                           2025.3.1
openai                                   2.45.0
openai-harmony                           0.0.8
opencv-contrib-python                    4.13.0.92
opencv-python                            5.0.0.93
opencv-python-headless                   5.0.0.93
openpyxl                                 3.1.5
opentelemetry-api                        1.44.0
opentelemetry-exporter-otlp              1.44.0
opentelemetry-exporter-otlp-proto-common 1.44.0
opentelemetry-exporter-otlp-proto-grpc   1.44.0
opentelemetry-exporter-otlp-proto-http   1.44.0
opentelemetry-proto                      1.44.0
opentelemetry-resourcedetector-gcp       1.12.0a0
opentelemetry-sdk                        1.44.0
opentelemetry-semantic-conventions       0.65b0
opentelemetry-semantic-conventions-ai    0.5.1
opt_einsum                               3.4.0
optax                                    0.2.8
optree                                   0.19.1
orbax-checkpoint                         0.12.1
orjson                                   3.11.9
ormsgpack                                1.12.2
osqp                                     1.1.3
outlines_core                            0.2.14
packaging                                26.2
pandas                                   2.2.2
pandas-datareader                        0.11.1
pandas-gbq                               0.30.0
pandas-stubs                             2.2.2.240909
pandocfilters                            1.5.1
panel                                    1.9.3
panel-material-ui                        0.14.0
param                                    2.4.1
parso                                    0.8.7
parsy                                    2.2
partd                                    1.4.2
partial-json-parser                      0.2.1.1.post7
patsy                                    1.0.2
peewee                                   4.2.2
peft                                     0.19.1
pexpect                                  4.9.0
pickleshare                              0.7.5
pillow                                   12.3.0
pip                                      24.1.2
platformdirs                             4.10.0
plotly                                   5.24.1
plotnine                                 0.14.5
pluggy                                   1.6.0
plum-dispatch                            2.9.0
pointpats                                2.5.5
polars                                   1.35.2
polars-runtime-32                        1.35.2
pooch                                    1.9.0
portpicker                               1.5.2
preshed                                  3.0.13
prettytable                              3.18.0
proglog                                  0.1.12
progressbar2                             4.5.0
prometheus_client                        0.25.0
prometheus-fastapi-instrumentator        8.1.0
promise                                  2.3
prompt_toolkit                           3.0.52
propcache                                0.5.2
prophet                                  1.3.0
proto-plus                               1.28.1
protobuf                                 5.29.6
psutil                                   5.9.5
psycopg2                                 2.9.12
psygnal                                  0.15.1
ptyprocess                               0.7.0
PuLP                                     3.3.2
py-cpuinfo                               9.0.0
py4j                                     0.10.9.9
pyarrow                                  18.1.0
pyasn1                                   0.6.4
pyasn1_modules                           0.4.2
pybase64                                 1.5.0
pycairo                                  1.29.0
pycocotools                              2.0.11
pycountry                                26.2.16
pycparser                                3.0
pycryptodomex                            3.23.0
pydantic                                 2.13.4
pydantic_core                            2.46.4
pydantic-extra-types                     2.11.1
pydantic-settings                        2.15.0
pydata-google-auth                       1.9.1
pydot                                    4.0.1
pydotplus                                2.0.2
PyDrive2                                 1.21.1
pydub                                    0.25.1
pyelftools                               0.33
pyerfa                                   2.0.1.5
pygame                                   2.6.1
pygit2                                   1.19.3
Pygments                                 2.20.0
PyGObject                                3.48.2
pyiceberg                                0.11.1
PyJWT                                    2.13.0
pylibcudf-cu12                           26.2.1
pylibcugraph-cu12                        26.2.0
pylibraft-cu12                           26.2.0
pymc                                     5.28.5
pymupdf                                  1.28.2
pynndescent                              0.6.0
pyogrio                                  0.13.0
pyomo                                    6.10.1
PyOpenGL                                 3.1.10
pyOpenSSL                                26.3.0
pyparsing                                3.3.2
pyperclip                                1.11.0
pyproj                                   3.7.2
pyroaring                                1.1.0
pysal                                    25.7
pyshp                                    3.1.4
PySocks                                  1.7.1
pyspark                                  4.0.3
pytensor                                 2.38.3
pytest                                   8.4.2
python-apt                               0.0.0
python-box                               7.4.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.2.2
python-fasthtml                          0.14.6
python-json-logger                       4.1.0
python-louvain                           0.16
python-multipart                         0.0.32
python-slugify                           8.0.4
python-snappy                            0.7.3
python-utils                             4.0.0
pytz                                     2025.2
pyviz_comms                              3.0.6
PyWavelets                               1.9.0
PyYAML                                   6.0.3
pyzmq                                    26.2.1
quack-kernels                            0.5.0
quantecon                                0.11.3
raft-dask-cu12                           26.2.0
rapids-dask-dependency                   26.2.0
rapids-logger                            0.2.3
rasterio                                 1.5.0
rasterstats                              0.21.0
ratelim                                  0.1.6
referencing                              0.37.0
regex                                    2025.11.3
requests                                 2.32.4
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
requirements-parser                      0.9.0
rfc3339-validator                        0.1.4
rfc3986-validator                        0.1.1
rfc3987-syntax                           1.1.0
rich                                     13.9.4
rich-toolkit                             0.20.3
rignore                                  0.8.1
rmm-cu12                                 26.2.0
roman-numerals                           4.1.0
roman-numerals-py                        4.1.0
rpds-py                                  2026.6.3
rpy2                                     3.5.17
rsa                                      4.9.1
rtree                                    1.4.1
safehttpx                                0.1.7
safetensors                              0.8.0
scikit-image                             0.25.2
scikit-learn                             1.6.1
scipy                                    1.16.3
scooby                                   0.11.2
scs                                      3.2.11
seaborn                                  0.13.2
SecretStorage                            3.5.0
segregation                              2.5.4
semantic-version                         2.10.0
Send2Trash                               2.1.0
sentence-transformers                    5.6.0
sentencepiece                            0.2.2
sentry-sdk                               2.65.0
setproctitle                             1.3.7
setuptools                               80.10.2
shap                                     0.52.0
shapely                                  2.1.2
shellingham                              1.5.4
simple-parsing                           0.1.8
simplejson                               4.1.1
simsimd                                  6.5.16
six                                      1.17.0
sklearn-compat                           0.1.6
sklearn-pandas                           2.2.0
slicer                                   0.0.8
smart_open                               8.0.0
smmap                                    5.0.3
sniffio                                  1.3.1
snowballstemmer                          3.1.1
sortedcontainers                         2.4.0
soundfile                                0.14.0
soupsieve                                2.8.4
soxr                                     1.1.0
spacy                                    3.8.14
spacy-legacy                             3.0.12
spacy-loggers                            1.0.5
spaghetti                                1.7.6
spanner-graph-notebook                   1.1.10
spglm                                    1.1.0
Sphinx                                   8.2.3
sphinxcontrib-applehelp                  2.0.0
sphinxcontrib-devhelp                    2.0.0
sphinxcontrib-htmlhelp                   2.1.0
sphinxcontrib-jsmath                     1.0.1
sphinxcontrib-qthelp                     2.0.0
sphinxcontrib-serializinghtml            2.0.0
spint                                    1.1.0
splot                                    1.1.7
spopt                                    0.7.0
spreg                                    1.9.0
SQLAlchemy                               2.0.51
sqlglot                                  25.20.2
sqlparse                                 0.5.5
srsly                                    2.5.3
sse-starlette                            3.4.8
stanio                                   0.5.1
starlette                                1.3.1
statsmodels                              0.14.6
strictyaml                               1.7.3
stringzilla                              4.6.2
stumpy                                   1.13.0
supervisor                               4.3.0
sympy                                    1.14.0
tables                                   3.10.2
tabulate                                 0.9.0
tbb                                      2022.3.1
tblib                                    3.2.2
tcmlib                                   1.5.0
tenacity                                 9.1.4
tensorboard                              2.20.0
tensorboard-data-server                  0.7.2
tensorflow                               2.20.0
tensorflow-datasets                      4.9.10
tensorflow-hub                           0.16.1
tensorflow-metadata                      1.21.0
tensorflow-probability                   0.25.0
tensorflow-text                          2.20.1
tensorstore                              0.1.84
termcolor                                3.3.0
terminado                                0.18.1
text-unidecode                           1.3
textblob                                 0.19.0
tf_keras                                 2.20.0
tf-slim                                  1.1.0
thinc                                    8.3.13
threadpoolctl                            3.6.0
tifffile                                 2026.4.11
tiktoken                                 0.13.0
tilelang                                 0.1.9
timm                                     1.0.28
tinycss2                                 1.5.1
tobler                                   0.14.0
tokenizers                               0.22.2
tokenspeed-mla                           0.1.2
tokenspeed-triton                        3.8.10.post20260721
toml                                     0.10.2
tomlkit                                  0.14.0
toolz                                    0.12.1
torch                                    2.11.0+cu128
torch_c_dlpack_ext                       0.1.5
torchao                                  0.10.0
torchaudio                               2.11.0+cu128
torchcodec                               0.11.0+cu128
torchdata                                0.11.0
torchsummary                             1.5.1
torchtune                                0.6.1
torchvision                              0.26.0+cu128
tornado                                  6.5.7
tqdm                                     4.67.3
traitlets                                5.7.1
traittypes                               0.2.3
transformers                             5.14.1
treelite                                 4.7.0
treescope                                0.1.10
triton                                   3.6.0
truststore                               0.10.4
tsfresh                                  0.21.2
tweepy                                   4.17.0
typeguard                                4.5.2
typer                                    0.26.8
types-pytz                               2026.2.0.20260518
types-setuptools                         82.0.0.20260518
typing_extensions                        4.16.0
typing-inspection                        0.4.2
tzdata                                   2026.3
tzlocal                                  5.4.4
uc-micro-py                              2.0.0
ucxx-cu12                                0.48.0
umap-learn                               0.5.12
umf                                      1.0.3
uri-template                             1.3.0
uritemplate                              4.2.0
urllib3                                  2.5.0
uuid_utils                               0.17.0
uvicorn                                  0.51.0
uvloop                                   0.22.1
vega-datasets                            0.9.0
vllm                                     0.22.1
wadllib                                  1.3.6
wandb                                    0.28.0
wasabi                                   1.1.3
watchdog                                 6.0.0
watchfiles                               1.2.0
wcwidth                                  0.8.2
weasel                                   1.0.0
webcolors                                25.10.0
webencodings                             0.5.1
websocket-client                         1.9.0
websockets                               15.0.1
Werkzeug                                 3.1.8
wheel                                    0.47.0
widgetsnbextension                       3.6.10
wordcloud                                1.9.6
wrapt                                    2.2.2
xarray                                   2025.12.0
xarray-einstats                          0.10.0
xgboost                                  3.3.0
xgrammar                                 0.2.3
xlrd                                     2.0.2
xxhash                                   3.8.1
xyzservices                              2026.3.0
yarl                                     1.24.2
ydf                                      0.15.0
ydf_tf                                   2.20.0
yellowbrick                              1.5
yfinance                                 0.2.66
z3-solver                                4.15.4.0
zict                                     3.0.0
zipp                                     4.1.0
zstandard                                0.25.0

"""Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.14.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 25.1.0
aiohappyeyeballs                         2.7.1
aiohttp                                  3.14.1
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.12.0
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
anthropic                                0.121.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.14.2
anywidget                                0.9.21
apache-tvm-ffi                           0.1.9
apsw                                     3.53.3.1
apswutils                                0.1.2
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
astor                                    0.8.1
astropy                                  7.2.2
astropy-iers-data                        0.2026.7.13.0.54.2
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    26.1.0
audioread                                3.1.0
Authlib                                  1.7.2
autograd                                 1.9.1
babel                                    2.18.0
backcall                                 0.2.0
beartype                                 0.22.9
beautifulsoup4                           4.13.5
betterproto                              2.0.0b6
bigframes                                2.42.0
bigquery-magics                          0.14.0
blake3                                   1.0.9
bleach                                   6.4.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.2.0
blosc2                                   4.8.0
bokeh                                    3.8.2
Bottleneck                               1.4.2
bqplot                                   0.12.47
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               6.2.6
catalogue                                2.0.10
cbor2                                    6.1.4
certifi                                  2026.6.17
cffi                                     2.1.0
chardet                                  5.2.0
charset-normalizer                       3.4.9
clarabel                                 0.11.1
click                                    8.4.2
cligj                                    0.7.2
cloudpathlib                             0.24.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.2.1
colorlover                               0.3.0
community                                1.0.0b1
compressed-tensors                       0.15.0.1
confection                               1.3.3
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             49.0.0
cucim-cu12                               26.2.0
cuda-bindings                            12.9.7
cuda-core                                0.3.2
cuda-pathfinder                          1.5.6
cuda-python                              12.9.7
cuda-tile                                1.5.0
cuda-toolkit                             12.8.1
cudf-cu12                                26.2.1
cudf-polars-cu12                         26.2.1
cufflinks                                0.17.3
cuml-cu12                                26.2.0
cupy-cuda12x                             14.0.1
curl_cffi                                0.15.0
cuvs-cu12                                26.2.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dask                                     2026.1.1
dask-cuda                                26.2.0
dask-cudf-cu12                           26.2.1
dataproc-spark-connect                   1.1.0
datasets                                 4.0.0
db-dtypes                                1.7.1
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
deprecation                              2.1.0
depyf                                    0.20.0
detect-installer                         0.1.0
diffusers                                0.39.0
dill                                     0.3.8
diskcache                                5.6.3
distributed                              2026.1.1
distributed-ucxx-cu12                    0.48.0
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.10
dnspython                                2.8.0
docstring_parser                         0.18.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.7.35
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.2
email-validator                          2.3.0
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.9.0
et_xmlfile                               2.0.0
etils                                    1.14.0
etuples                                  0.3.10
Farama-Notifications                     0.0.6
fastai                                   2.8.7
fastapi                                  0.139.0
fastapi-cli                              0.0.32
fastapi-cloud-cli                        0.23.0
fastar                                   0.11.0
fastcore                                 2.0.5
fastdownload                             0.0.7
fastjsonschema                           2.21.2
fastlite                                 0.2.4
fastprogress                             1.1.6
fastsafetensors                          0.3.3
fasttransform                            0.0.2
filelock                                 3.29.7
firebase-admin                           6.9.0
flashinfer-cubin                         0.6.11.post2
flashinfer-python                        0.6.11.post2
Flask                                    3.1.3
flatbuffers                              25.12.19
flax                                     0.11.2
folium                                   0.20.0
fonttools                                4.63.0
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.7.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.2
geemap                                   0.38.3
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.4
geopy                                    2.4.1
gguf                                     0.19.0
giddy                                    2.3.6
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.51
glob2                                    0.7
google                                   3.0.0
google-adk                               2.4.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.30.3
google-api-python-client                 2.198.0
google-auth                              2.49.0
google-auth-httplib2                     0.4.0
google-auth-oauthlib                     1.4.0
google-cloud-bigquery                    3.42.2
google-cloud-bigquery-connection         1.22.0
google-cloud-bigquery-storage            2.39.0
google-cloud-core                        2.6.0
google-cloud-dataproc                    5.28.0
google-cloud-datastore                   2.25.0
google-cloud-firestore                   2.27.0
google-cloud-functions                   1.24.0
google-cloud-language                    2.21.0
google-cloud-monitoring                  2.31.0
google-cloud-resource-manager            1.18.0
google-cloud-spanner                     3.68.0
google-cloud-storage                     3.13.0
google-cloud-translate                   3.27.0
google-colab                             1.0.0
google-crc32c                            1.8.0
google-genai                             2.11.0
google-generativeai                      0.8.6
google-pasta                             0.2.0
google-resumable-media                   2.10.0
googleapis-common-protos                 1.75.0
googledrivedownloader                    1.1.0
gradio                                   6.22.0
gradio_client                            2.6.0
grain                                    0.2.18
graphviz                                 0.21
greenlet                                 3.5.3
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.4
grpc-interceptor                         0.15.4
grpcio                                   1.82.1
grpcio-status                            1.71.2
grpclib                                  0.4.9
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.3.0
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.8.1
h5py                                     3.16.0
hdbscan                                  0.8.44
hf-gradio                                0.4.1
hf-xet                                   1.5.1
highspy                                  1.15.1
holidays                                 0.100
holoviews                                1.23.1
hpack                                    4.2.0
html5lib                                 1.1
httpcore                                 1.0.9
httpcore2                                2.5.0
httpimport                               1.4.1
httplib2                                 0.32.0
httptools                                0.8.0
httpx                                    0.28.1
httpx2                                   2.5.0
huggingface_hub                          1.23.0
humanize                                 4.16.0
humming-kernels                          0.1.2
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.18
ijson                                    3.5.1
ImageIO                                  2.37.3
imageio-ffmpeg                           0.6.0
imagesize                                2.0.0
imbalanced-learn                         0.14.2
immutabledict                            4.3.1
importlib_metadata                       9.0.0
importlib_resources                      7.1.0
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.3
intel-openmp                             2025.3.3
interegular                              0.3.3
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.1.2
jaraco.functools                         4.5.0
jax                                      0.7.2
jax-cuda12-pjrt                          0.7.2
jax-cuda12-plugin                        0.7.2
jaxlib                                   0.7.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.16.0
jmespath                                 1.1.0
joblib                                   1.5.3
joserfc                                  1.7.3
jsonpatch                                1.33
jsonpickle                               4.1.2
jsonpointer                              3.1.1
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.1
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.20.0
jupyter_server_terminals                 0.5.4
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.19.4
kaggle                                   2.0.2
kagglehub                                1.0.2
kagglesdk                                0.1.23
keras                                    3.13.2
keras-hub                                0.26.0
keras-nlp                                0.26.0
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.5.0
langchain                                1.3.13
langchain-core                           1.4.9
langchain-protocol                       0.0.18
langgraph                                1.2.9
langgraph-checkpoint                     4.1.1
langgraph-prebuilt                       1.1.0
langgraph-sdk                            0.4.2
langsmith                                0.10.2
lark                                     1.2.2
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy-loader                              0.5
libclang                                 18.1.1
libcudf-cu12                             26.2.1
libcugraph-cu12                          26.2.0
libcuml-cu12                             26.2.0
libcuvs-cu12                             26.2.0
libkvikio-cu12                           26.2.0
libpysal                                 4.14.1
libraft-cu12                             26.2.0
librmm-cu12                              26.2.0
librosa                                  0.11.0
libucx-cu12                              1.19.0
libucxx-cu12                             0.48.0
lightgbm                                 4.6.0
linkify-it-py                            2.1.0
llguidance                               1.7.6
llvmlite                                 0.47.0
lm-format-enforcer                       0.11.3
locket                                   1.0.0
logical-unification                      0.4.7
loguru                                   0.7.3
lxml                                     6.1.1
Mako                                     1.1.3
mapclassify                              2.10.0
Markdown                                 3.10.2
markdown-it-py                           4.2.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.2
matplotlib-venn                          1.1.2
mcp                                      2.0.0
mcp-types                                2.0.0
mdit-py-plugins                          0.6.1
mdurl                                    0.1.2
mgwr                                     2.2.1
miniKanren                               1.0.5
missingno                                0.5.2
mistral_common                           1.11.7
mistune                                  3.3.3
mizani                                   0.13.5
mkl                                      2025.3.1
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
mmh3                                     5.2.1
model-hosting-container-standards        0.1.16
momepy                                   0.11.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.2.1
msgspec                                  0.21.1
multidict                                6.7.1
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.13
murmurhash                               1.0.15
music21                                  9.9.2
namex                                    0.1.0
narwhals                                 2.24.0
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.4
nbconvert                                7.17.1
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6.1
nh3                                      0.3.6
nibabel                                  5.4.2
ninja                                    1.13.0
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.65.0
numba-cuda                               0.22.2
numexpr                                  2.14.1
numpy                                    2.0.2
nvidia-cublas-cu12                       12.8.4.1
nvidia-cuda-cccl                         13.3.3.4.1
nvidia-cuda-cccl-cu12                    12.9.27
nvidia-cuda-crt                          13.3.73
nvidia-cuda-cupti-cu12                   12.8.90
nvidia-cuda-nvcc                         13.3.73
nvidia-cuda-nvcc-cu12                    12.8.93
nvidia-cuda-nvrtc                        13.3.33
nvidia-cuda-nvrtc-cu12                   12.8.93
nvidia-cuda-runtime                      13.3.29
nvidia-cuda-runtime-cu12                 12.8.90
nvidia-cudnn-cu12                        9.19.0.56
nvidia-cudnn-frontend                    1.18.0
nvidia-cufft-cu12                        11.3.3.83
nvidia-cufile-cu12                       1.13.1.3
nvidia-curand-cu12                       10.3.9.90
nvidia-cusolver-cu12                     11.7.3.90
nvidia-cusparse-cu12                     12.5.8.93
nvidia-cusparselt-cu12                   0.7.1
nvidia-cutlass-dsl                       4.5.2
nvidia-cutlass-dsl-libs-base             4.5.2
nvidia-cutlass-dsl-libs-cu13             4.5.2
nvidia-libnvcomp-cu12                    5.1.0.21
nvidia-ml-py                             13.610.43
nvidia-nccl-cu12                         2.28.9
nvidia-nvimgcodec-cu12                   0.7.0.11
nvidia-nvjitlink-cu12                    12.8.93
nvidia-nvshmem-cu12                      3.4.5
nvidia-nvtx-cu12                         12.8.90
nvidia-nvvm                              13.3.73
nvtx                                     0.2.15
nx-cugraph-cu12                          26.2.0
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.1
onemkl-license                           2025.3.1
openai                                   2.45.0
openai-harmony                           0.0.8
opencv-contrib-python                    4.13.0.92
opencv-python                            5.0.0.93
opencv-python-headless                   5.0.0.93
openpyxl                                 3.1.5
opentelemetry-api                        1.44.0
opentelemetry-exporter-otlp              1.44.0
opentelemetry-exporter-otlp-proto-common 1.44.0
opentelemetry-exporter-otlp-proto-grpc   1.44.0
opentelemetry-exporter-otlp-proto-http   1.44.0
opentelemetry-proto                      1.44.0
opentelemetry-resourcedetector-gcp       1.12.0a0
opentelemetry-sdk                        1.44.0
opentelemetry-semantic-conventions       0.65b0
opentelemetry-semantic-conventions-ai    0.5.1
opt_einsum                               3.4.0
optax                                    0.2.8
optree                                   0.19.1
orbax-checkpoint                         0.12.1
orjson                                   3.11.9
ormsgpack                                1.12.2
osqp                                     1.1.3
outlines_core                            0.2.14
packaging                                26.2
pandas                                   2.2.2
pandas-datareader                        0.11.1
pandas-gbq                               0.30.0
pandas-stubs                             2.2.2.240909
pandocfilters                            1.5.1
panel                                    1.9.3
panel-material-ui                        0.14.0
param                                    2.4.1
parso                                    0.8.7
parsy                                    2.2
partd                                    1.4.2
partial-json-parser                      0.2.1.1.post7
patsy                                    1.0.2
peewee                                   4.2.2
peft                                     0.19.1
pexpect                                  4.9.0
pickleshare                              0.7.5
pillow                                   12.3.0
pip                                      24.1.2
platformdirs                             4.10.0
plotly                                   5.24.1
plotnine                                 0.14.5
pluggy                                   1.6.0
plum-dispatch                            2.9.0
pointpats                                2.5.5
polars                                   1.35.2
polars-runtime-32                        1.35.2
pooch                                    1.9.0
portpicker                               1.5.2
preshed                                  3.0.13
prettytable                              3.18.0
proglog                                  0.1.12
progressbar2                             4.5.0
prometheus_client                        0.25.0
prometheus-fastapi-instrumentator        8.1.0
promise                                  2.3
prompt_toolkit                           3.0.52
propcache                                0.5.2
prophet                                  1.3.0
proto-plus                               1.28.1
protobuf                                 5.29.6
psutil                                   5.9.5
psycopg2                                 2.9.12
psygnal                                  0.15.1
ptyprocess                               0.7.0
PuLP                                     3.3.2
py-cpuinfo                               9.0.0
py4j                                     0.10.9.9
pyarrow                                  18.1.0
pyasn1                                   0.6.4
pyasn1_modules                           0.4.2
pybase64                                 1.5.0
pycairo                                  1.29.0
pycocotools                              2.0.11
pycountry                                26.2.16
pycparser                                3.0
pycryptodomex                            3.23.0
pydantic                                 2.13.4
pydantic_core                            2.46.4
pydantic-extra-types                     2.11.1
pydantic-settings                        2.15.0
pydata-google-auth                       1.9.1
pydot                                    4.0.1
pydotplus                                2.0.2
PyDrive2                                 1.21.1
pydub                                    0.25.1
pyelftools                               0.33
pyerfa                                   2.0.1.5
pygame                                   2.6.1
pygit2                                   1.19.3
Pygments                                 2.20.0
PyGObject                                3.48.2
pyiceberg                                0.11.1
PyJWT                                    2.13.0
pylibcudf-cu12                           26.2.1
pylibcugraph-cu12                        26.2.0
pylibraft-cu12                           26.2.0
pymc                                     5.28.5
pymupdf                                  1.28.2
pynndescent                              0.6.0
pyogrio                                  0.13.0
pyomo                                    6.10.1
PyOpenGL                                 3.1.10
pyOpenSSL                                26.3.0
pyparsing                                3.3.2
pyperclip                                1.11.0
pyproj                                   3.7.2
pyroaring                                1.1.0
pysal                                    25.7
pyshp                                    3.1.4
PySocks                                  1.7.1
pyspark                                  4.0.3
pytensor                                 2.38.3
pytest                                   8.4.2
python-apt                               0.0.0
python-box                               7.4.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.2.2
python-fasthtml                          0.14.6
python-json-logger                       4.1.0
python-louvain                           0.16
python-multipart                         0.0.32
python-slugify                           8.0.4
python-snappy                            0.7.3
python-utils                             4.0.0
pytz                                     2025.2
pyviz_comms                              3.0.6
PyWavelets                               1.9.0
PyYAML                                   6.0.3
pyzmq                                    26.2.1
quack-kernels                            0.5.0
quantecon                                0.11.3
raft-dask-cu12                           26.2.0
rapids-dask-dependency                   26.2.0
rapids-logger                            0.2.3
rasterio                                 1.5.0
rasterstats                              0.21.0
ratelim                                  0.1.6
referencing                              0.37.0
regex                                    2025.11.3
requests                                 2.32.4
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
requirements-parser                      0.9.0
rfc3339-validator                        0.1.4
rfc3986-validator                        0.1.1
rfc3987-syntax                           1.1.0
rich                                     13.9.4
rich-toolkit                             0.20.3
rignore                                  0.8.1
rmm-cu12                                 26.2.0
roman-numerals                           4.1.0
roman-numerals-py                        4.1.0
rpds-py                                  2026.6.3
rpy2                                     3.5.17
rsa                                      4.9.1
rtree                                    1.4.1
safehttpx                                0.1.7
safetensors                              0.8.0
scikit-image                             0.25.2
scikit-learn                             1.6.1
scipy                                    1.16.3
scooby                                   0.11.2
scs                                      3.2.11
seaborn                                  0.13.2
SecretStorage                            3.5.0
segregation                              2.5.4
semantic-version                         2.10.0
Send2Trash                               2.1.0
sentence-transformers                    5.6.0
sentencepiece                            0.2.2
sentry-sdk                               2.65.0
setproctitle                             1.3.7
setuptools                               80.10.2
shap                                     0.52.0
shapely                                  2.1.2
shellingham                              1.5.4
simple-parsing                           0.1.8
simplejson                               4.1.1
simsimd                                  6.5.16
six                                      1.17.0
sklearn-compat                           0.1.6
sklearn-pandas                           2.2.0
slicer                                   0.0.8
smart_open                               8.0.0
smmap                                    5.0.3
sniffio                                  1.3.1
snowballstemmer                          3.1.1
sortedcontainers                         2.4.0
soundfile                                0.14.0
soupsieve                                2.8.4
soxr                                     1.1.0
spacy                                    3.8.14
spacy-legacy                             3.0.12
spacy-loggers                            1.0.5
spaghetti                                1.7.6
spanner-graph-notebook                   1.1.10
spglm                                    1.1.0
Sphinx                                   8.2.3
sphinxcontrib-applehelp                  2.0.0
sphinxcontrib-devhelp                    2.0.0
sphinxcontrib-htmlhelp                   2.1.0
sphinxcontrib-jsmath                     1.0.1
sphinxcontrib-qthelp                     2.0.0
sphinxcontrib-serializinghtml            2.0.0
spint                                    1.1.0
splot                                    1.1.7
spopt                                    0.7.0
spreg                                    1.9.0
SQLAlchemy                               2.0.51
sqlglot                                  25.20.2
sqlparse                                 0.5.5
srsly                                    2.5.3
sse-starlette                            3.4.8
stanio                                   0.5.1
starlette                                1.3.1
statsmodels                              0.14.6
strictyaml                               1.7.3
stringzilla                              4.6.2
stumpy                                   1.13.0
supervisor                               4.3.0
sympy                                    1.14.0
tables                                   3.10.2
tabulate                                 0.9.0
tbb                                      2022.3.1
tblib                                    3.2.2
tcmlib                                   1.5.0
tenacity                                 9.1.4
tensorboard                              2.20.0
tensorboard-data-server                  0.7.2
tensorflow                               2.20.0
tensorflow-datasets                      4.9.10
tensorflow-hub                           0.16.1
tensorflow-metadata                      1.21.0
tensorflow-probability                   0.25.0
tensorflow-text                          2.20.1
tensorstore                              0.1.84
termcolor                                3.3.0
terminado                                0.18.1
text-unidecode                           1.3
textblob                                 0.19.0
tf_keras                                 2.20.0
tf-slim                                  1.1.0
thinc                                    8.3.13
threadpoolctl                            3.6.0
tifffile                                 2026.4.11
tiktoken                                 0.13.0
tilelang                                 0.1.9
timm                                     1.0.28
tinycss2                                 1.5.1
tobler                                   0.14.0
tokenizers                               0.22.2
tokenspeed-mla                           0.1.2
tokenspeed-triton                        3.8.10.post20260721
toml                                     0.10.2
tomlkit                                  0.14.0
toolz                                    0.12.1
torch                                    2.11.0+cu128
torch_c_dlpack_ext                       0.1.5
torchao                                  0.10.0
torchaudio                               2.11.0+cu128
torchcodec                               0.11.0+cu128
torchdata                                0.11.0
torchsummary                             1.5.1
torchtune                                0.6.1
torchvision                              0.26.0+cu128
tornado                                  6.5.7
tqdm                                     4.67.3
traitlets                                5.7.1
traittypes                               0.2.3
transformers                             5.14.1
treelite                                 4.7.0
treescope                                0.1.10
triton                                   3.6.0
truststore                               0.10.4
tsfresh                                  0.21.2
tweepy                                   4.17.0
typeguard                                4.5.2
typer                                    0.26.8
types-pytz                               2026.2.0.20260518
types-setuptools                         82.0.0.20260518
typing_extensions                        4.16.0
typing-inspection                        0.4.2
tzdata                                   2026.3
tzlocal                                  5.4.4
uc-micro-py                              2.0.0
ucxx-cu12                                0.48.0
umap-learn                               0.5.12
umf                                      1.0.3
uri-template                             1.3.0
uritemplate                              4.2.0
urllib3                                  2.5.0
uuid_utils                               0.17.0
uvicorn                                  0.51.0
uvloop                                   0.22.1
vega-datasets                            0.9.0
vllm                                     0.22.1
wadllib                                  1.3.6
wandb                                    0.28.0
wasabi                                   1.1.3
watchdog                                 6.0.0
watchfiles                               1.2.0
wcwidth                                  0.8.2
weasel                                   1.0.0
webcolors                                25.10.0
webencodings                             0.5.1
websocket-client                         1.9.0
websockets                               15.0.1
Werkzeug                                 3.1.8
wheel                                    0.47.0
widgetsnbextension                       3.6.10
wordcloud                                1.9.6
wrapt                                    2.2.2
xarray                                   2025.12.0
xarray-einstats                          0.10.0
xgboost                                  3.3.0
xgrammar                                 0.2.3
xlrd                                     2.0.2
xxhash                                   3.8.1
xyzservices                              2026.3.0
yarl                                     1.24.2
ydf                                      0.15.0
ydf_tf                                   2.20.0
yellowbrick                              1.5
yfinance                                 0.2.66
z3-solver                                4.15.4.0
zict                                     3.0.0
zipp                                     4.1.0
zstandard                                0.25.0

"""

!pip list

import torch

print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "NO GPU")

!nvidia-smi
!nvcc --version

import torch

print("PyTorch:", torch.__version__)
print("CUDA used by PyTorch:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

!pip install -U \
  "transformers>=5.13.0,<6" \
  "accelerate>=1.12.0" \
  "torchvision>=0.25.0,<0.27" \
  "Pillow>=10.0.0" \
  "PyMuPDF>=1.24.0,<2"

import torch

print("PyTorch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))
print("CUDA available:", torch.cuda.is_available())

"""### شغال تنزيل النمخوذج"""

from transformers import AutoProcessor, AutoModelForMultimodalLM

MODEL = "ATH-MaaS/OvisOCR2"

processor = AutoProcessor.from_pretrained(MODEL)

model = AutoModelForMultimodalLM.from_pretrained(
    MODEL,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

print("OvisOCR2 loaded successfully!")

from PIL import Image

image = Image.open("/content/1.png").convert("RGB")

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image
            },
            {
                "type": "text",
                "text": "Extract all readable content from this image in natural human reading order."
            }
        ]
    }
]

inputs = processor.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

with torch.inference_mode():
    outputs = model.generate(
        **inputs,
        max_new_tokens=4096,
    )

result = processor.decode(
    outputs[0][inputs["input_ids"].shape[-1]:],
    skip_special_tokens=True,
)

print(result)

from PIL import Image
from vllm import LLM, SamplingParams

self.model = LLM(
    model=model_name_or_path,
    tensor_parallel_size=1,
    gpu_memory_utilization=0.8,
    gdn_prefill_backend="triton"
)

















"""شغال"""

# Commented out IPython magic to ensure Python compatibility.
# 1. تحميل ملفات المساحة من هجينج فيس
!git clone https://huggingface.co/spaces/ATH-MaaS/OvisOCR2

# 2. الدخول إلى مجلد المشروع
# %cd OvisOCR2



"""شغال"""

!pip install -r /content/OvisOCR2/requirements.txt

"""### شغال تنزيل النمخوذج"""

from transformers import AutoProcessor, AutoModelForMultimodalLM

MODEL = "ATH-MaaS/OvisOCR2"

processor = AutoProcessor.from_pretrained(MODEL)

model = AutoModelForMultimodalLM.from_pretrained(
    MODEL,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

print("OvisOCR2 loaded successfully!")

"""### شغال"""

from google.colab import files
from PIL import Image

uploaded = files.upload()

image_path = next(iter(uploaded))
image = Image.open(image_path).convert("RGB")

print("Image:", image_path)
print("Size:", image.size)

"""### شغال نص فقط"""

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image
            },
            {
                "type": "text",
                "text": "Extract all readable content from this image in natural human reading order and output it as Markdown."
            }
        ]
    }
]

inputs = processor.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

with torch.inference_mode():
    outputs = model.generate(
        **inputs,
        max_new_tokens=4096,
    )

result = processor.decode(
    outputs[0][inputs["input_ids"].shape[-1]:],
    skip_special_tokens=True,
)

print(result)

"""### شغال"""

!pip install -q -U \
    "transformers>=5.13.0,<6" \
    "accelerate>=1.12.0" \
    "gradio>=6.0.0" \
    "PyMuPDF>=1.24.0,<2" \
    "Pillow>=10.0.0"

"""### شغال"""

import os
import io
import re
import time
import base64
import threading
from pathlib import Path
from typing import Iterator, Any

import torch
import fitz
import gradio as gr

from PIL import Image, ImageOps
from transformers import (
    AutoProcessor,
    Qwen3_5ForConditionalGeneration,
    TextIteratorStreamer,
)

# ============================================================
# CONFIG
# ============================================================

MODEL_ID = "ATH-MaaS/OvisOCR2"

MAX_NEW_TOKENS = 16384

# نفس الفكرة الموجودة في Space الرسمي
MIN_PIXELS = 448 * 448
MAX_PIXELS = 2880 * 2880

PDF_RENDER_SCALE = 2.0
MAX_PDF_PAGES = 50

# ============================================================
# CUDA / MEMORY
# ============================================================

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA غير متاحة. فعّل T4 من Runtime > Change runtime type."
    )

print("=" * 60)
print("OvisOCR2 - Google Colab T4")
print("=" * 60)
print("PyTorch :", torch.__version__)
print("CUDA    :", torch.version.cuda)
print("GPU     :", torch.cuda.get_device_name(0))
print(
    "VRAM    :",
    round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2),
    "GB",
)
print("=" * 60)


# ============================================================
# LOAD MODEL
# ============================================================

print("\nLoading OvisOCR2...")

processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    min_pixels=MIN_PIXELS,
    max_pixels=MAX_PIXELS,
)

model = Qwen3_5ForConditionalGeneration.from_pretrained(
    MODEL_ID,
    dtype=torch.bfloat16,
    attn_implementation="sdpa",
)

model = model.to("cuda")
model.eval()

print("\nOvisOCR2 loaded successfully!")
print("Device:", model.device)
print("=" * 60)


# ============================================================
# OCR PROMPT
# ============================================================

OCR_PROMPT = """
Extract all readable content from the image in natural human reading order
and output the result as a single Markdown document.

For charts or images, represent them using an HTML image tag:
<img src="images/bbox_{left}_{top}_{right}_{bottom}.jpg" />

where left, top, right, bottom are bounding box coordinates scaled to [0, 1000).

Format formulas as LaTeX.

Format tables as HTML:
<table>...</table>

Transcribe all other text as standard Markdown.

Preserve the original text without translation or paraphrasing.
""".strip()


# ============================================================
# HELPERS
# ============================================================

def get_file_path(file_obj):
    """
    Get actual uploaded file path from Gradio.
    Supports both string paths and Gradio file objects.
    """

    if file_obj is None:
        raise ValueError("لم يتم رفع أي ملف.")

    if isinstance(file_obj, str):
        return file_obj

    if isinstance(file_obj, dict):
        path = file_obj.get("path")
        if path:
            return str(path)

    path = getattr(file_obj, "path", None)

    if path:
        return str(path)

    raise ValueError("تعذر الحصول على مسار الملف المرفوع.")


def document_info(path):
    """
    Detect whether uploaded file is an image or PDF.
    """

    path = str(path)
    suffix = Path(path).suffix.lower()

    # Check PDF header
    try:
        with open(path, "rb") as f:
            header = f.read(5)
    except Exception as e:
        raise ValueError("تعذر قراءة الملف.") from e

    if suffix == ".pdf" or header == b"%PDF-":

        with fitz.open(path) as doc:
            total_pages = doc.page_count

        if total_pages < 1:
            raise ValueError("ملف PDF لا يحتوي على صفحات.")

        if total_pages > MAX_PDF_PAGES:
            raise ValueError(
                f"الحد الأقصى هو {MAX_PDF_PAGES} صفحة. "
                f"الملف يحتوي على {total_pages} صفحة."
            )

        return "pdf", total_pages

    # Validate image
    try:
        with Image.open(path) as img:
            img.verify()
    except Exception as e:
        raise ValueError(
            "الملف يجب أن يكون PNG أو JPEG أو WebP أو PDF."
        ) from e

    return "image", 1


def load_page(path, document_type, page_index):
    """
    Load one page as PIL RGB image.
    """

    if document_type == "pdf":

        with fitz.open(path) as doc:

            page = doc.load_page(page_index)

            pix = page.get_pixmap(
                matrix=fitz.Matrix(
                    PDF_RENDER_SCALE,
                    PDF_RENDER_SCALE,
                ),
                colorspace=fitz.csRGB,
                alpha=False,
            )

            return Image.frombytes(
                "RGB",
                (pix.width, pix.height),
                pix.samples,
            )

    with Image.open(path) as img:
        return ImageOps.exif_transpose(img).convert("RGB")


def generation_token_ids():
    tokenizer = processor.tokenizer

    return {
        "eos_token_id": int(tokenizer.eos_token_id),
        "pad_token_id": int(tokenizer.pad_token_id),
    }


# ============================================================
# MODEL INPUT
# ============================================================

def create_inputs(image):
    """
    Create OvisOCR2 multimodal inputs.
    """

    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": image,
                },
                {
                    "type": "text",
                    "text": OCR_PROMPT,
                },
            ],
        }
    ]

    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt",
        enable_thinking=False,
    )

    return inputs.to(model.device)


# ============================================================
# OCR STREAM
# ============================================================

def run_ocr_stream(image):
    """
    Run OCR and stream text progressively.
    """

    inputs = create_inputs(image)

    streamer = TextIteratorStreamer(
        processor.tokenizer,
        skip_prompt=True,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )

    errors = []

    def generate():

        try:

            with torch.inference_mode():

                model.generate(
                    **inputs,
                    streamer=streamer,
                    max_new_tokens=MAX_NEW_TOKENS,
                    do_sample=False,
                    temperature=None,
                    top_p=None,
                    top_k=None,
                    **generation_token_ids(),
                )

        except Exception as e:

            errors.append(e)

            try:
                streamer.on_finalized_text(
                    "",
                    stream_end=True,
                )
            except Exception:
                pass

    worker = threading.Thread(
        target=generate,
        daemon=True,
    )

    worker.start()

    text = ""

    for fragment in streamer:

        text += fragment

        yield text

    worker.join()

    if errors:
        raise RuntimeError(
            f"فشل تشغيل OvisOCR2: {errors[0]}"
        )

    return text


# ============================================================
# BBOX MATERIALIZATION
# ============================================================

BBOX_PATTERN = re.compile(
    r'<img\s+src=["\']images/bbox_'
    r'(\d+)_(\d+)_(\d+)_(\d+)\.jpg["\']\s*/?>',
    flags=re.IGNORECASE,
)


def materialize_bbox_images(markdown, page_image):
    """
    Replace bbox references produced by OvisOCR2
    with embedded base64 JPEG crops.
    """

    if not markdown:
        return markdown

    width, height = page_image.size

    def replace(match):

        left, top, right, bottom = (
            int(x) for x in match.groups()
        )

        x1 = max(
            0,
            min(
                width,
                round(left * width / 1000),
            ),
        )

        y1 = max(
            0,
            min(
                height,
                round(top * height / 1000),
            ),
        )

        x2 = max(
            0,
            min(
                width,
                round(right * width / 1000),
            ),
        )

        y2 = max(
            0,
            min(
                height,
                round(bottom * height / 1000),
            ),
        )

        if x2 <= x1 or y2 <= y1:
            return match.group(0)

        crop = page_image.crop(
            (x1, y1, x2, y2)
        ).convert("RGB")

        crop.thumbnail(
            (1200, 1200),
            Image.Resampling.BILINEAR,
        )

        buffer = io.BytesIO()

        crop.save(
            buffer,
            format="JPEG",
            quality=85,
        )

        encoded = base64.b64encode(
            buffer.getvalue()
        ).decode("ascii")

        return (
            '<img '
            f'src="data:image/jpeg;base64,{encoded}" '
            'alt="Visual region" '
            'style="max-width:100%;height:auto;" />'
        )

    return BBOX_PATTERN.sub(
        replace,
        markdown,
    )


# ============================================================
# SINGLE IMAGE OCR
# ============================================================

def ocr_image(file_obj):

    if file_obj is None:
        return "", "ارفع صورة أولًا."

    start = time.time()

    try:

        path = get_file_path(file_obj)

        document_type, total_pages = document_info(path)

        if document_type != "image":
            return "", "هذا زر الصور فقط. استخدم زر PDF."

        image = load_page(
            path,
            "image",
            0,
        )

        print(
            f"[OCR] Image size: {image.size}",
            flush=True,
        )

        final_text = ""

        for partial in run_ocr_stream(image):

            final_text = partial

            # Gradio يحتاج return في نهاية الوظيفة،
            # لذلك لا نستخدم yield هنا.
            # يتم تحديث النتيجة بعد انتهاء التوليد.

        rendered = materialize_bbox_images(
            final_text,
            image,
        )

        elapsed = time.time() - start

        status = (
            f"تم الانتهاء.\n"
            f"الوقت: {elapsed:.1f} ثانية\n"
            f"عدد الأحرف: {len(final_text):,}"
        )

        return rendered, status

    except Exception as e:

        return (
            "",
            f"ERROR: {type(e).__name__}: {e}",
        )


# ============================================================
# PDF OCR
# ============================================================

def ocr_pdf(file_obj, start_page, page_count):

    if file_obj is None:
        return "", "ارفع PDF أولًا."

    start_time = time.time()

    try:

        path = get_file_path(file_obj)

        document_type, total_pages = document_info(path)

        if document_type != "pdf":
            return "", "الملف ليس PDF."

        start_page = int(start_page) - 1
        page_count = int(page_count)

        if start_page < 0:
            start_page = 0

        if start_page >= total_pages:
            return (
                "",
                f"الصفحة المطلوبة غير موجودة. "
                f"الملف يحتوي على {total_pages} صفحات.",
            )

        end_page = min(
            total_pages,
            start_page + page_count,
        )

        all_pages = []

        print(
            f"[PDF] Processing pages "
            f"{start_page + 1}-{end_page}/{total_pages}",
            flush=True,
        )

        for page_index in range(
            start_page,
            end_page,
        ):

            page_number = page_index + 1

            print(
                f"[OCR] Page {page_number}/{end_page}",
                flush=True,
            )

            image = load_page(
                path,
                "pdf",
                page_index,
            )

            final_text = ""

            for partial in run_ocr_stream(image):
                final_text = partial

            rendered = materialize_bbox_images(
                final_text,
                image,
            )

            all_pages.append(
                f"<!-- Page {page_number} -->\n\n"
                f"{rendered}"
            )

            # تنظيف الذاكرة بعد كل صفحة
            del image

            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        result = "\n\n---\n\n".join(
            all_pages
        )

        elapsed = time.time() - start_time

        status = (
            f"تم الانتهاء.\n"
            f"الصفحات: {start_page + 1}-{end_page}\n"
            f"إجمالي الصفحات في PDF: {total_pages}\n"
            f"الوقت: {elapsed:.1f} ثانية\n"
            f"عدد الأحرف: {len(result):,}"
        )

        return result, status

    except Exception as e:

        return (
            "",
            f"ERROR: {type(e).__name__}: {e}",
        )


# ============================================================
# PDF INFO
# ============================================================

def pdf_info(file_obj):

    if file_obj is None:
        return "لم يتم اختيار PDF."

    try:

        path = get_file_path(file_obj)

        document_type, total_pages = document_info(path)

        if document_type != "pdf":
            return "الملف ليس PDF."

        return (
            f"PDF صحيح.\n"
            f"عدد الصفحات: {total_pages}"
        )

    except Exception as e:

        return f"ERROR: {e}"


# ============================================================
# GRADIO UI
# ============================================================

CUSTOM_CSS = """
#title {
    text-align: center;
    margin-bottom: 10px;
}

.status {
    white-space: pre-wrap;
}

textarea {
    font-family: monospace !important;
}

.output-markdown {
    min-height: 500px;
}
"""


with gr.Blocks(
    title="OvisOCR2 - Colab T4",
    theme=gr.themes.Soft(),
    css=CUSTOM_CSS,
) as demo:

    gr.Markdown(
        """
        # 🔎 OvisOCR2 OCR

        ### تشغيل OvisOCR2 محليًا على Google Colab T4

        النموذج يعمل بالكامل داخل جلسة Colab.
        """
        ,
        elem_id="title",
    )

    with gr.Tabs():

        # ====================================================
        # IMAGE TAB
        # ====================================================

        with gr.Tab("📷 صورة"):

            with gr.Row():

                with gr.Column():

                    image_input = gr.File(
                        label="ارفع صورة",
                        file_types=[
                            ".png",
                            ".jpg",
                            ".jpeg",
                            ".webp",
                        ],
                        type="filepath",
                    )

                    image_button = gr.Button(
                        "🚀 تشغيل OCR",
                        variant="primary",
                    )

                    image_status = gr.Textbox(
                        label="الحالة",
                        interactive=False,
                        elem_classes="status",
                    )

                with gr.Column():

                    image_output = gr.Markdown(
                        label="OCR Result",
                        elem_classes="output-markdown",
                    )

            image_button.click(
                fn=ocr_image,
                inputs=image_input,
                outputs=[
                    image_output,
                    image_status,
                ],
            )

        # ====================================================
        # PDF TAB
        # ====================================================

        with gr.Tab("📄 PDF"):

            with gr.Row():

                with gr.Column():

                    pdf_input = gr.File(
                        label="ارفع PDF",
                        file_types=[".pdf"],
                        type="filepath",
                    )

                    pdf_info_button = gr.Button(
                        "🔍 معلومات PDF",
                    )

                    pdf_info_output = gr.Textbox(
                        label="معلومات الملف",
                        interactive=False,
                    )

                    with gr.Row():

                        pdf_start = gr.Number(
                            label="صفحة البداية",
                            value=1,
                            minimum=1,
                            precision=0,
                        )

                        pdf_count = gr.Number(
                            label="عدد الصفحات",
                            value=1,
                            minimum=1,
                            maximum=50,
                            precision=0,
                        )

                    pdf_button = gr.Button(
                        "🚀 تشغيل OCR على PDF",
                        variant="primary",
                    )

                    pdf_status = gr.Textbox(
                        label="الحالة",
                        interactive=False,
                        elem_classes="status",
                    )

                with gr.Column():

                    pdf_output = gr.Markdown(
                        label="OCR Result",
                        elem_classes="output-markdown",
                    )

            pdf_info_button.click(
                fn=pdf_info,
                inputs=pdf_input,
                outputs=pdf_info_output,
            )

            pdf_button.click(
                fn=ocr_pdf,
                inputs=[
                    pdf_input,
                    pdf_start,
                    pdf_count,
                ],
                outputs=[
                    pdf_output,
                    pdf_status,
                ],
            )

    gr.Markdown(
        """
        ---
        **Model:** `ATH-MaaS/OvisOCR2`

        **Backend:** Transformers

        **GPU:** NVIDIA Tesla T4
        """
    )


# ============================================================
# LAUNCH
# ============================================================

print("\nStarting Gradio...")

demo.launch(
    share=True,
    debug=True,
    show_error=True,
)

